config/routes.rb
Rails.application.routes.draw do
  root  'about#index'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about', to:'about#index', via:'get'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :talk
  resources :profiles
  

end

app/models/talk.rb
class Talk < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
  validates :content, length: { maximum: 2995}
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]

  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
  end

  # GET /talks/new
  def new
    @talk = Talk.new
  end

  # GET /talks/1/edit
  def edit
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(talk_params)

    respond_to do |format|
      if @talk.save
        format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @talk }
      else
        format.html { render action: 'new' }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talks/1
  # PATCH/PUT /talks/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk.destroy
    respond_to do |format|
      format.html { redirect_to talks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talk
      @talk = Talk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talk_params
      params.require(:talk).permit(:content, :image, :user_id)
    end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/_talks.html.erb
<li>
  <%= link_to profile_image_for(tweet.user) %>
  <span class="user">
    <%= link_to tweet.user.name, tweet.user %>
  </span>
  <span class="content"><%= tweet.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tweet.created_at) %> ago.
  </span>
</li>

app/views/talks/edit.html.erb
<h1>Editing talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<h1>Listing talks</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Image</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talk| %>
      <tr>
        <td><%= talk.content %></td>
        <td><%= talk.image %></td>
        <td><%= talk.user_id %></td>
        <td><%= link_to 'Show', talk %></td>
        <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
        <td><%= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<h1>New talk</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @talk.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @talk.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @talk.user_id %>
</p>

<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>